export { HeroSection }      from './HeroSection'
export { SquadSection }     from './SquadSection'
export { StandingsSection } from './StandingsSection'
export { HistorySection }   from './HistorySection'
export { CtaBanner }        from './CtaBanner'
export { ContactSection }   from './ContactSection'
export { PlayerCard }       from './PlayerCard'
